/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_anominy_stringcure_UStringCure */

#ifndef _Included_io_github_anominy_stringcure_UStringCure
#define _Included_io_github_anominy_stringcure_UStringCure
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_anominy_stringcure_UStringCure
 * Method:    transform
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_github_anominy_stringcure_UStringCure_transform
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
